### ISSUE TITLE
Could we integrate fs/mac-profile?

### ISSUE THREAD

**Issue by timurvafin** [fs/fs-tool#76]
@vast is it possible to integrate https://github.com/fs/mac-profile into fs-tool?

**Comment by vast** [comment]
@timurvafin, sure, but it doesn't look like a good fit for it. `fs-tool` contains tools for everyday use. Is `mac-profile` supposed to be used on everyday basis?

What do you think about installing it with homebrew?

**Comment by timurvafin** [comment]
@vast agreed, it's going to be used very rare I guess. Let's keep it separate.
