### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by maxinspace** [fs/fs-tool#78]
That's happened on brew cleanup on my system.

``` bash
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/fs/homebrew-fstool/fs-tool.rb:8:in `<class:FsTool>'
Please report this to the fs/fstool tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/fs/homebrew-fstool/fs-tool.rb:8:in `<class:FsTool>'
Please report this to the fs/fstool tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/fs/homebrew-fstool/fs-tool.rb:8:in `<class:FsTool>'
Please report this to the fs/fstool tap!
```

**Comment by maxprokopiev** [comment]
@maximlarionov this is related to the [brew cask](https://github.com/fs/homebrew-fstool) repo

I fixed the issue in the [last](https://github.com/fs/homebrew-fstool/commit/07208e05753e680f9a1cadd13e2eaa9ec199e1be) [two](https://github.com/fs/homebrew-fstool/commit/f9ae047d567f8c4128cd7959b39fd0ed1711d55f) commits, although you have to

```
brew untap fs/fstool
brew tap fs/fstool
```

to pull the latest changes, good luck and thanks for reporting!

**Comment by maxinspace** [comment]
@maxprokopiev thanks for fixing and explaining the problem :)

**Comment by kevwilson** [comment]
I will be checking emails intermittently. 

If you have an urgent issue please contact me, leaving a voicemail if you are unable to get through, explaining the issue and I will respond as promptly as possible.
